# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 22:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('quality', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('directions', models.TextField()),
                ('details', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restroom.Restroom')),
            ],
        ),
    ]
